# Generated by Django 4.2.2 on 2023-07-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='carbohydrate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='protein',
            field=models.FloatField(),
        ),
    ]
