# Generated by Django 4.2.2 on 2023-07-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_meals_carbohydrate_alter_meals_fat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
