# Generated by Django 4.1.10 on 2023-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_meals_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='offeredFood',
            field=models.BooleanField(default=False),
        ),
    ]
