# Generated by Django 4.1.10 on 2023-07-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_meal_offeredfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
